"""
Pydantic schemas for API request/response validation.
"""

from app.schemas.common import PaginatedResponse, SuccessResponse, ErrorResponse
from app.schemas.knowledge import (
    KnowledgeListParams,
    KnowledgeItemCreate,
    KnowledgeItemUpdate,
    KnowledgeItemResponse,
    KnowledgeItemDetailResponse,
    VariantCreate,
    VariantResponse,
    RelationshipCreate,
    RelationshipResponse,
    RelatedItemResponse,
    CategoryCreate,
    CategoryUpdate,
    CategoryResponse,
    CategoryTreeResponse,
    VersionResponse,
)
from app.schemas.staging import (
    StagingListParams,
    StagingReviewRequest,
    StagingEditRequest,
    StagingItemResponse,
    StagingCountsResponse,
    StagingListResponse,
    StagingReviewResponse,
)
from app.schemas.search import (
    SearchRequest,
    SearchResult,
    SearchResponse,
    ContextSearchRequest,
    ContextItem,
    ContextSearchResponse,
)
from app.schemas.metrics import (
    MetricsSummaryResponse,
    TypeDistribution,
    StatusDistribution,
    KnowledgeHitStats,
    TopItemsResponse,
    DailyHitStats,
    DailyTrendResponse,
    TagStats,
    TagStatsResponse,
    ItemStatsResponse,
)
from app.schemas.settings import (
    SearchSettings,
    PipelineSettings,
    MaintenanceSettings,
    SettingsResponse,
    SettingsUpdateRequest,
)
from app.schemas.nodes import (
    FAQContent,
    PlaybookContent,
    PermissionRuleContent,
    EntityContent,
    SchemaIndexContent,
    SchemaFieldContent,
    ExampleContent,
    ConceptContent,
    NodeListParams,
    NodeCreate,
    NodeUpdate,
    NodeResponse,
    NodeDetailResponse,
    NodeSearchResult,
    NodeSearchResponse,
    NodeVersionResponse,
)
from app.schemas.edges import (
    EdgeCreate,
    EdgeBulkCreate,
    EdgeUpdate,
    EdgeResponse,
    EdgeListParams,
    EdgeListResponse,
)
from app.schemas.tenant import (
    TenantCreate,
    TenantUpdate,
    TenantResponse,
    TenantListResponse,
    UserTenantAccessCreate,
    UserTenantAccessUpdate,
    UserTenantAccessResponse,
    UserTenantsResponse,
)
from app.schemas.context import (
    ContextRequest,
    ContextResponse,
    EntryPointResult,
    ContextNodeResult,
    EntityResult,
    ContextStats,
)

__all__ = [
    # Common
    "PaginatedResponse",
    "SuccessResponse",
    "ErrorResponse",
    # Knowledge
    "KnowledgeListParams",
    "KnowledgeItemCreate",
    "KnowledgeItemUpdate",
    "KnowledgeItemResponse",
    "KnowledgeItemDetailResponse",
    "VariantCreate",
    "VariantResponse",
    "RelationshipCreate",
    "RelationshipResponse",
    "RelatedItemResponse",
    "CategoryCreate",
    "CategoryUpdate",
    "CategoryResponse",
    "CategoryTreeResponse",
    "VersionResponse",
    # Staging
    "StagingListParams",
    "StagingReviewRequest",
    "StagingEditRequest",
    "StagingItemResponse",
    "StagingCountsResponse",
    "StagingListResponse",
    "StagingReviewResponse",
    # Search
    "SearchRequest",
    "SearchResult",
    "SearchResponse",
    "ContextSearchRequest",
    "ContextItem",
    "ContextSearchResponse",
    # Metrics
    "MetricsSummaryResponse",
    "TypeDistribution",
    "StatusDistribution",
    "KnowledgeHitStats",
    "TopItemsResponse",
    "DailyHitStats",
    "DailyTrendResponse",
    "TagStats",
    "TagStatsResponse",
    "ItemStatsResponse",
    # Settings
    "SearchSettings",
    "PipelineSettings",
    "MaintenanceSettings",
    "SettingsResponse",
    "SettingsUpdateRequest",
    # Knowledge Verse Nodes
    "FAQContent",
    "PlaybookContent",
    "PermissionRuleContent",
    "EntityContent",
    "SchemaIndexContent",
    "SchemaFieldContent",
    "ExampleContent",
    "ConceptContent",
    "NodeListParams",
    "NodeCreate",
    "NodeUpdate",
    "NodeResponse",
    "NodeDetailResponse",
    "NodeSearchResult",
    "NodeSearchResponse",
    "NodeVersionResponse",
    # Knowledge Verse Edges
    "EdgeCreate",
    "EdgeBulkCreate",
    "EdgeUpdate",
    "EdgeResponse",
    "EdgeListParams",
    "EdgeListResponse",
    # Knowledge Verse Tenants
    "TenantCreate",
    "TenantUpdate",
    "TenantResponse",
    "TenantListResponse",
    "UserTenantAccessCreate",
    "UserTenantAccessUpdate",
    "UserTenantAccessResponse",
    "UserTenantsResponse",
    # Knowledge Verse Context
    "ContextRequest",
    "ContextResponse",
    "EntryPointResult",
    "ContextNodeResult",
    "EntityResult",
    "ContextStats",
]
