import type {
  LegacyKnowledgeItem,
  KnowledgeCategory,
  KnowledgeVariant,
  KnowledgeRelationship,
  StagingKnowledgeItem,
  KnowledgeHitStats,
  DailyHitStats,
} from '@/types/knowledge'

// ==================== Categories ====================

export const mockCategories: KnowledgeCategory[] = [
  {
    id: 1,
    name: 'Purchasing',
    slug: 'purchasing',
    description: 'Questions about purchasing processes and policies',
    default_visibility: 'internal',
    sort_order: 1,
  },
  {
    id: 2,
    name: 'Vendors',
    slug: 'vendors',
    description: 'Vendor management and onboarding',
    default_visibility: 'internal',
    sort_order: 2,
  },
  {
    id: 3,
    name: 'Approvals',
    slug: 'approvals',
    description: 'Approval workflows and thresholds',
    default_visibility: 'internal',
    sort_order: 3,
  },
  {
    id: 4,
    name: 'IT Equipment',
    slug: 'it-equipment',
    description: 'IT hardware and software procurement',
    parent_id: 1,
    default_visibility: 'internal',
    sort_order: 4,
  },
  {
    id: 5,
    name: 'Travel & Expenses',
    slug: 'travel-expenses',
    description: 'Travel booking and expense policies',
    default_visibility: 'internal',
    sort_order: 5,
  },
]

// ==================== Knowledge Items ====================

export const mockKnowledgeItems: LegacyKnowledgeItem[] = [
  {
    id: 1,
    knowledge_type: 'faq',
    category_id: 1,
    category: mockCategories[0],
    title: 'How do I create a purchase order?',
    summary: 'Step-by-step guide to creating purchase orders in the system',
    content: {
      question: 'How do I create a purchase order?',
      answer:
        'To create a purchase order, navigate to Purchasing > Create PO in the main menu. Select your vendor from the dropdown, add line items with quantities and prices, then click Submit for Approval. The system will route the PO to the appropriate approver based on the total amount.',
    },
    tags: ['purchasing', 'po', 'how-to', 'getting-started'],
    visibility: 'internal',
    status: 'published',
    owner_id: 'user-001',
    team_id: 'procurement',
    created_by: 'admin',
    created_at: '2024-12-01T10:00:00Z',
    updated_at: '2024-12-15T14:30:00Z',
    variants_count: 3,
    relationships_count: 2,
    hits_count: 156,
  },
  {
    id: 2,
    knowledge_type: 'faq',
    category_id: 3,
    category: mockCategories[2],
    title: 'What are the approval thresholds for purchase orders?',
    summary: 'Explains the different approval levels based on PO amounts',
    content: {
      question: 'What are the approval thresholds for purchase orders?',
      answer:
        'Purchase orders require different approval levels based on the total amount:\n\n- Up to $5,000: Manager approval\n- $5,001 - $10,000: Director approval\n- $10,001 - $50,000: VP approval\n- Over $50,000: CFO approval\n\nEmergency purchases may have expedited approval paths.',
    },
    tags: ['purchasing', 'approval', 'threshold', 'policy'],
    visibility: 'internal',
    status: 'published',
    created_by: 'admin',
    created_at: '2024-11-15T09:00:00Z',
    updated_at: '2024-12-10T11:00:00Z',
    variants_count: 2,
    relationships_count: 4,
    hits_count: 243,
  },
  {
    id: 3,
    knowledge_type: 'faq',
    category_id: 2,
    category: mockCategories[1],
    title: 'How do I add a new vendor to the system?',
    summary: 'Process for onboarding new vendors',
    content: {
      question: 'How do I add a new vendor to the system?',
      answer:
        'To add a new vendor:\n\n1. Submit a Vendor Request Form from Procurement Portal\n2. Provide vendor details: name, address, tax ID, banking info\n3. Finance will verify tax documentation (W-9 for US vendors)\n4. Compliance will run a background check\n5. Once approved, Master Data team creates the vendor record\n\nTypical turnaround time is 3-5 business days.',
    },
    tags: ['vendor', 'onboarding', 'process'],
    visibility: 'internal',
    status: 'published',
    created_by: 'procurement-lead',
    created_at: '2024-10-20T08:00:00Z',
    updated_at: '2024-11-25T16:45:00Z',
    variants_count: 1,
    relationships_count: 3,
    hits_count: 89,
  },
  {
    id: 4,
    knowledge_type: 'business_rule',
    category_id: 3,
    category: mockCategories[2],
    title: 'Large Purchase Order VP Approval Rule',
    summary: 'Orders exceeding $10,000 require VP-level approval',
    content: {
      condition: 'Purchase order total amount exceeds $10,000 USD',
      action: 'Route to VP of the requesting department for approval',
      exceptions: [
        'Pre-approved annual contracts',
        'Emergency purchases with documented justification',
        'IT infrastructure covered under pre-approved budget',
      ],
    },
    tags: ['purchasing', 'approval', 'threshold', 'business-rule'],
    visibility: 'internal',
    status: 'published',
    created_by: 'compliance',
    created_at: '2024-09-01T10:00:00Z',
    variants_count: 0,
    relationships_count: 2,
    hits_count: 67,
  },
  {
    id: 5,
    knowledge_type: 'faq',
    category_id: 4,
    category: mockCategories[3],
    title: 'How do I request a new laptop?',
    summary: 'Process for requesting IT equipment',
    content: {
      question: 'How do I request a new laptop?',
      answer:
        'To request a new laptop:\n\n1. Open a ticket in IT Service Desk\n2. Select "Hardware Request" > "Laptop"\n3. Choose from approved models (Standard, Developer, Executive)\n4. Provide business justification\n5. Manager approval will be requested automatically\n\nDelivery typically takes 1-2 weeks for in-stock models.',
    },
    tags: ['it', 'laptop', 'hardware', 'equipment'],
    visibility: 'internal',
    status: 'published',
    created_by: 'it-support',
    created_at: '2024-11-01T11:00:00Z',
    variants_count: 2,
    relationships_count: 1,
    hits_count: 312,
  },
  {
    id: 6,
    knowledge_type: 'context',
    category_id: 2,
    category: mockCategories[1],
    title: 'Vendor: Dell Technologies',
    summary: 'Dell is our primary IT hardware supplier',
    content: {
      entity_type: 'vendor',
      entity_id: 'VENDOR-DELL-001',
      description:
        'Dell Technologies is our primary IT hardware supplier. They are a preferred vendor with negotiated enterprise pricing. Contract includes 15% discount on bulk orders over $10,000. Support SLA: 4-hour response for critical issues.',
    },
    tags: ['vendor', 'it-hardware', 'preferred', 'dell'],
    visibility: 'internal',
    status: 'published',
    created_by: 'vendor-manager',
    created_at: '2024-08-15T09:00:00Z',
    variants_count: 0,
    relationships_count: 3,
    hits_count: 45,
  },
  {
    id: 7,
    knowledge_type: 'procedure',
    category_id: 2,
    category: mockCategories[1],
    title: 'Vendor Onboarding Process',
    summary: 'Complete workflow for onboarding new vendors',
    content: {
      steps: [
        { order: 1, action: 'Submit vendor request form', note: 'Include all required documentation' },
        { order: 2, action: 'Verify tax documentation (W-9/W-8)', note: 'Finance team responsibility' },
        { order: 3, action: 'Run background and compliance check', note: '2-3 business days' },
        { order: 4, action: 'Negotiate and finalize contract terms', note: 'Legal review required for contracts > $50k' },
        { order: 5, action: 'Procurement Manager approval' },
        { order: 6, action: 'Create vendor master record', note: 'Master Data team' },
        { order: 7, action: 'Set up payment terms in AP system' },
      ],
    },
    tags: ['vendor', 'onboarding', 'process', 'procedure'],
    visibility: 'internal',
    status: 'published',
    created_by: 'process-owner',
    created_at: '2024-07-01T10:00:00Z',
    variants_count: 0,
    relationships_count: 4,
    hits_count: 78,
  },
  {
    id: 8,
    knowledge_type: 'faq',
    category_id: 5,
    category: mockCategories[4],
    title: 'How do I submit an expense report?',
    summary: 'Guide to submitting expense reports for reimbursement',
    content: {
      question: 'How do I submit an expense report?',
      answer:
        'To submit an expense report:\n\n1. Go to Expenses > Create Report\n2. Select the expense category and cost center\n3. Upload receipts for all expenses over $25\n4. Add business justification for each line item\n5. Submit for manager approval\n\nReimbursement typically processes within 5-7 business days after approval.',
    },
    tags: ['expenses', 'reimbursement', 'travel', 'how-to'],
    visibility: 'internal',
    status: 'published',
    created_by: 'finance-admin',
    created_at: '2024-10-01T14:00:00Z',
    variants_count: 1,
    relationships_count: 0,
    hits_count: 198,
  },
  {
    id: 9,
    knowledge_type: 'faq',
    category_id: 1,
    category: mockCategories[0],
    title: 'Can I split a purchase order across multiple cost centers?',
    summary: 'Explains multi-cost-center PO handling',
    content: {
      question: 'Can I split a purchase order across multiple cost centers?',
      answer:
        'Yes, you can split a purchase order across multiple cost centers. When creating a PO, use the "Split Allocation" option on each line item to assign percentages to different cost centers. The system will automatically route approvals to all relevant cost center owners.',
    },
    tags: ['purchasing', 'po', 'cost-center', 'allocation'],
    visibility: 'internal',
    status: 'published',
    created_by: 'admin',
    created_at: '2024-11-20T09:30:00Z',
    variants_count: 0,
    relationships_count: 1,
    hits_count: 34,
  },
  {
    id: 10,
    knowledge_type: 'faq',
    category_id: 1,
    category: mockCategories[0],
    title: 'What is the difference between a PO and a PR?',
    summary: 'Explains Purchase Order vs Purchase Requisition',
    content: {
      question: 'What is the difference between a PO and a PR?',
      answer:
        'A Purchase Requisition (PR) is an internal request to buy something. A Purchase Order (PO) is the official document sent to the vendor to order goods/services.\n\nWorkflow: You create a PR -> Gets approved -> Procurement converts it to a PO -> PO is sent to vendor.',
    },
    tags: ['purchasing', 'po', 'pr', 'basics'],
    visibility: 'internal',
    status: 'draft',
    created_by: 'training',
    created_at: '2024-12-20T10:00:00Z',
    variants_count: 0,
    relationships_count: 2,
    hits_count: 0,
  },
]

// ==================== Variants ====================

export const mockVariants: KnowledgeVariant[] = [
  {
    id: 1,
    knowledge_item_id: 1,
    variant_text: 'How to create a PO?',
    source: 'ticket_pipeline',
    source_reference: 'TKT-2024-1234',
    created_at: '2024-12-05T10:00:00Z',
  },
  {
    id: 2,
    knowledge_item_id: 1,
    variant_text: 'Steps to make a purchase order',
    source: 'ticket_pipeline',
    source_reference: 'TKT-2024-1456',
    created_at: '2024-12-08T14:00:00Z',
  },
  {
    id: 3,
    knowledge_item_id: 1,
    variant_text: 'Purchase order creation process',
    source: 'manual',
    created_by: 'admin',
    created_at: '2024-12-10T09:00:00Z',
  },
  {
    id: 4,
    knowledge_item_id: 2,
    variant_text: 'Who needs to approve my PO?',
    source: 'ticket_pipeline',
    created_at: '2024-11-20T11:00:00Z',
  },
  {
    id: 5,
    knowledge_item_id: 2,
    variant_text: 'PO approval limits',
    source: 'manual',
    created_by: 'admin',
    created_at: '2024-11-25T09:00:00Z',
  },
  {
    id: 6,
    knowledge_item_id: 5,
    variant_text: 'Need a new laptop',
    source: 'ticket_pipeline',
    created_at: '2024-11-10T15:00:00Z',
  },
  {
    id: 7,
    knowledge_item_id: 5,
    variant_text: 'How to get a work laptop?',
    source: 'ticket_pipeline',
    created_at: '2024-11-15T11:00:00Z',
  },
]

// ==================== Relationships ====================

export const mockRelationships: KnowledgeRelationship[] = [
  {
    id: 1,
    source_id: 1,
    target_id: 2,
    relationship_type: 'related',
    weight: 1.0,
    is_bidirectional: true,
    is_auto_generated: false,
    created_by: 'admin',
    created_at: '2024-12-01T10:00:00Z',
  },
  {
    id: 2,
    source_id: 2,
    target_id: 4,
    relationship_type: 'implements',
    weight: 1.0,
    is_bidirectional: false,
    is_auto_generated: false,
    created_by: 'admin',
    created_at: '2024-12-01T10:00:00Z',
  },
  {
    id: 3,
    source_id: 3,
    target_id: 7,
    relationship_type: 'see_also',
    weight: 0.8,
    is_bidirectional: true,
    is_auto_generated: false,
    created_by: 'admin',
    created_at: '2024-11-25T09:00:00Z',
  },
  {
    id: 4,
    source_id: 5,
    target_id: 6,
    relationship_type: 'related',
    weight: 0.9,
    is_bidirectional: true,
    is_auto_generated: true,
    created_at: '2024-11-15T10:00:00Z',
  },
]

// ==================== Staging Items ====================

export const mockStagingItems: StagingKnowledgeItem[] = [
  {
    id: 1,
    knowledge_type: 'faq',
    category_id: 1,
    title: 'How do I cancel a purchase order?',
    summary: 'Steps to cancel an existing PO',
    content: {
      question: 'How do I cancel a purchase order?',
      answer:
        'To cancel a purchase order, go to Purchasing > My POs, find the order, and click Cancel. Note: You can only cancel POs that havent been sent to the vendor. For POs already with the vendor, you need to request a formal cancellation through Procurement.',
    },
    tags: ['purchasing', 'po', 'cancel'],
    source_ticket_id: 'TKT-2024-2001',
    confidence: 0.87,
    status: 'pending',
    action: 'new',
    similarity: 0.45,
    created_at: '2024-12-22T10:00:00Z',
  },
  {
    id: 2,
    knowledge_type: 'faq',
    category_id: 3,
    title: 'What happens if my PO is rejected?',
    summary: 'Explains the rejection workflow',
    content: {
      question: 'What happens if my PO is rejected?',
      answer:
        'If your PO is rejected, youll receive an email notification with the rejection reason. You can edit the PO to address the concerns and resubmit it for approval. Common rejection reasons include: insufficient budget, missing justification, or wrong vendor selection.',
    },
    tags: ['purchasing', 'approval', 'rejection'],
    source_ticket_id: 'TKT-2024-2015',
    confidence: 0.92,
    status: 'pending',
    action: 'new',
    similarity: 0.38,
    created_at: '2024-12-22T14:30:00Z',
  },
  {
    id: 3,
    knowledge_type: 'faq',
    category_id: 1,
    title: 'How do I create a purchase order?',
    summary: 'New phrasing from support ticket',
    content: {
      question: 'I need to buy office supplies, how do I do that?',
      answer:
        'To purchase office supplies, create a purchase order in the system. Navigate to Purchasing > Create PO, select Office Supplies vendor, add items, and submit for approval.',
    },
    tags: ['purchasing', 'po', 'office-supplies'],
    source_ticket_id: 'TKT-2024-2022',
    confidence: 0.78,
    status: 'pending',
    action: 'add_variant',
    merge_with_id: 1,
    similarity: 0.89,
    created_at: '2024-12-23T09:15:00Z',
  },
  {
    id: 4,
    knowledge_type: 'faq',
    category_id: 2,
    title: 'How do I check if a vendor is approved?',
    summary: 'Finding approved vendor status',
    content: {
      question: 'How do I check if a vendor is approved?',
      answer:
        'To check vendor approval status, go to Vendors > Search, enter the vendor name. The status column will show Approved, Pending, or Not Found. Only approved vendors can be used on purchase orders.',
    },
    tags: ['vendor', 'approval', 'status'],
    source_ticket_id: 'TKT-2024-2030',
    confidence: 0.85,
    status: 'pending',
    action: 'new',
    similarity: 0.52,
    created_at: '2024-12-23T11:00:00Z',
  },
  {
    id: 5,
    knowledge_type: 'faq',
    category_id: 3,
    title: 'PO approval thresholds update',
    summary: 'Updated approval information',
    content: {
      question: 'What are the current PO approval limits?',
      answer:
        'Current approval thresholds: Manager up to $5,000, Director $5,001-$10,000, VP $10,001-$50,000, CFO over $50,000. These were updated in Q4 2024.',
    },
    tags: ['purchasing', 'approval', 'threshold'],
    source_ticket_id: 'TKT-2024-2045',
    confidence: 0.91,
    status: 'pending',
    action: 'merge',
    merge_with_id: 2,
    similarity: 0.94,
    created_at: '2024-12-23T15:30:00Z',
  },
]

// ==================== Hit Statistics ====================

export const mockHitStats: KnowledgeHitStats[] = [
  {
    id: 5,
    knowledge_type: 'faq',
    title: 'How do I request a new laptop?',
    tags: ['it', 'laptop', 'hardware', 'equipment'],
    total_hits: 312,
    unique_sessions: 245,
    days_with_hits: 28,
    last_hit_at: '2024-12-23T16:45:00Z',
    avg_similarity: 0.87,
    primary_retrieval_method: 'hybrid_search',
  },
  {
    id: 2,
    knowledge_type: 'faq',
    title: 'What are the approval thresholds for purchase orders?',
    tags: ['purchasing', 'approval', 'threshold', 'policy'],
    total_hits: 243,
    unique_sessions: 198,
    days_with_hits: 30,
    last_hit_at: '2024-12-23T17:00:00Z',
    avg_similarity: 0.82,
    primary_retrieval_method: 'hybrid_search',
  },
  {
    id: 8,
    knowledge_type: 'faq',
    title: 'How do I submit an expense report?',
    tags: ['expenses', 'reimbursement', 'travel', 'how-to'],
    total_hits: 198,
    unique_sessions: 156,
    days_with_hits: 25,
    last_hit_at: '2024-12-23T15:30:00Z',
    avg_similarity: 0.85,
    primary_retrieval_method: 'hybrid_search',
  },
  {
    id: 1,
    knowledge_type: 'faq',
    title: 'How do I create a purchase order?',
    tags: ['purchasing', 'po', 'how-to', 'getting-started'],
    total_hits: 156,
    unique_sessions: 134,
    days_with_hits: 22,
    last_hit_at: '2024-12-23T14:00:00Z',
    avg_similarity: 0.89,
    primary_retrieval_method: 'hybrid_search',
  },
  {
    id: 3,
    knowledge_type: 'faq',
    title: 'How do I add a new vendor to the system?',
    tags: ['vendor', 'onboarding', 'process'],
    total_hits: 89,
    unique_sessions: 76,
    days_with_hits: 18,
    last_hit_at: '2024-12-23T11:00:00Z',
    avg_similarity: 0.81,
    primary_retrieval_method: 'hybrid_search',
  },
]

export const mockDailyStats: DailyHitStats[] = [
  { date: '2024-12-17', total_hits: 45, unique_sessions: 38, by_type: { faq: 25, permission: 8, schema: 5, example: 4, playbook: 3 } },
  { date: '2024-12-18', total_hits: 52, unique_sessions: 44, by_type: { faq: 30, permission: 10, schema: 6, example: 3, playbook: 3 } },
  { date: '2024-12-19', total_hits: 38, unique_sessions: 32, by_type: { faq: 22, permission: 7, schema: 4, example: 3, playbook: 2 } },
  { date: '2024-12-20', total_hits: 61, unique_sessions: 52, by_type: { faq: 35, permission: 12, schema: 7, example: 4, playbook: 3 } },
  { date: '2024-12-21', total_hits: 23, unique_sessions: 20, by_type: { faq: 13, permission: 4, schema: 3, example: 2, playbook: 1 } },
  { date: '2024-12-22', total_hits: 18, unique_sessions: 15, by_type: { faq: 10, permission: 3, schema: 2, example: 2, playbook: 1 } },
  { date: '2024-12-23', total_hits: 67, unique_sessions: 58, by_type: { faq: 38, permission: 13, schema: 8, example: 5, playbook: 3 } },
]

// ==================== All Tags ====================

export const mockAllTags: string[] = [
  'purchasing',
  'po',
  'how-to',
  'getting-started',
  'approval',
  'threshold',
  'policy',
  'vendor',
  'onboarding',
  'process',
  'procedure',
  'business-rule',
  'it',
  'laptop',
  'hardware',
  'equipment',
  'expenses',
  'reimbursement',
  'travel',
  'cost-center',
  'allocation',
  'pr',
  'basics',
  'preferred',
  'dell',
  'office-supplies',
  'cancel',
  'rejection',
  'status',
]
