"""
Enumeration types for the knowledge base system.
"""

from enum import Enum


class KnowledgeType(str, Enum):
    """Types of knowledge items supported by the system (legacy)."""
    FAQ = "faq"
    POLICY = "policy"
    PROCEDURE = "procedure"
    BUSINESS_RULE = "business_rule"
    CONTEXT = "context"
    PERMISSION = "permission"
    REFERENCE = "reference"
    TROUBLESHOOTING = "troubleshooting"


class NodeType(str, Enum):
    """Types of nodes in the Knowledge Verse graph."""
    FAQ = "faq"
    PLAYBOOK = "playbook"
    PERMISSION_RULE = "permission_rule"
    SCHEMA_INDEX = "schema_index"
    SCHEMA_FIELD = "schema_field"
    EXAMPLE = "example"
    ENTITY = "entity"
    CONCEPT = "concept"
    QUERY_PLAN = "query_plan"
    PLAN_VERSION = "plan_version"
    PROMPT_TEMPLATE = "prompt_template"


class EdgeType(str, Enum):
    """Types of edges connecting nodes in the Knowledge Verse graph."""
    RELATED = "related"           # General bidirectional relationship
    PARENT = "parent"             # Hierarchical (parent→child)
    EXAMPLE_OF = "example_of"     # Example demonstrates schema
    SHARED_TAG = "shared_tag"     # Auto: computed from tag overlap
    SIMILAR = "similar"           # Auto: computed from embedding similarity


class TenantRole(str, Enum):
    """Role types for user tenant access."""
    VIEWER = "viewer"
    EDITOR = "editor"
    ADMIN = "admin"


class KnowledgeStatus(str, Enum):
    """Publication status of knowledge items."""
    DRAFT = "draft"
    PUBLISHED = "published"
    ARCHIVED = "archived"


class Visibility(str, Enum):
    """Visibility/access level of knowledge items."""
    PUBLIC = "public"
    INTERNAL = "internal"
    RESTRICTED = "restricted"


class StagingStatus(str, Enum):
    """Status of staging items awaiting review."""
    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"


class StagingAction(str, Enum):
    """Action to take for a staging item."""
    NEW = "new"           # Create new knowledge item
    MERGE = "merge"       # Merge with existing item
    ADD_VARIANT = "add_variant"  # Add as question variant


class RelationshipType(str, Enum):
    """Types of relationships between knowledge items."""
    RELATED = "related"       # Semantically similar
    PARENT = "parent"         # Hierarchical parent
    CHILD = "child"           # Hierarchical child
    SEE_ALSO = "see_also"     # Cross-reference
    SUPERSEDES = "supersedes" # Replaces older item
    DEPENDS_ON = "depends_on" # Prerequisite relationship
    IMPLEMENTS = "implements" # Implements a policy/rule
    GOVERNS = "governs"       # Business rule governing entity


class VariantSource(str, Enum):
    """Source of question variants."""
    MANUAL = "manual"     # Manually created
    PIPELINE = "pipeline" # Generated by pipeline
    IMPORT = "import"     # Imported from external source
